In [2]:
import pandas as pd
messages=pd.read_csv('SMSSpamCollection.txt',
                    sep='\t',names=["label","message"])

In [3]:
messages

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [4]:
## Data Cleaning And Preprocessing
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\KIIT\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [5]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [6]:
corpus=[]
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-z]',' ',messages['message'][i])
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [7]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

In [17]:
y=pd.get_dummies(messages['label'],dtype=int)


In [18]:
y=y.iloc[:,0].values

In [19]:
y


array([1, 1, 0, ..., 1, 1, 1])

In [20]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.20)

In [21]:
## Create the Bag OF Words model
from sklearn.feature_extraction.text import CountVectorizer
## for Binary BOW enable binary=True
cv=CountVectorizer(max_features=2500,ngram_range=(1,2))


len(X_train),len(y_train)

(4457, 4457)

In [22]:
## independent features
X_train=cv.fit_transform(X_train).toarray()
X_test=cv.transform(X_test).toarray()

In [23]:
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000, 
    formatter=dict(float=lambda x: "%.3g" % x))
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [24]:
cv.vocabulary_

{'one': 1500,
 'best': 166,
 'cute': 478,
 'wen': 2385,
 'die': 547,
 'dont': 574,
 'come': 383,
 'near': 1414,
 'bodi': 188,
 'bcoz': 151,
 'hand': 907,
 'may': 1281,
 'ur': 2245,
 'tear': 2079,
 'time': 2140,
 'gud': 891,
 'ni': 1434,
 'gud ni': 893,
 'ya': 2473,
 'break': 208,
 'hurri': 998,
 'home': 964,
 'done': 573,
 'lol': 1193,
 'know': 1093,
 'hey': 934,
 'someon': 1937,
 'great': 864,
 'love': 1214,
 'anytim': 75,
 'anyway': 77,
 'far': 684,
 'studi': 2017,
 'visit': 2304,
 'especi': 639,
 'sinc': 1897,
 'talk': 2066,
 'boston': 197,
 'person': 1563,
 'statement': 1986,
 'chang': 318,
 'realiz': 1706,
 'said': 1791,
 'nyc': 1475,
 'say': 1807,
 'ard': 88,
 'like': 1166,
 'dat': 495,
 'lor': 1203,
 'juz': 1070,
 'meet': 1290,
 'mrt': 1377,
 'station': 1988,
 'dun': 598,
 'haf': 901,
 'like dat': 1167,
 'still': 1993,
 'get': 788,
 'good': 838,
 'aiyo': 45,
 'pleas': 1597,
 'got': 851,
 'meh': 1293,
 'tape': 2068,
 'could': 438,
 'mind': 1316,
 'go': 811,
 'bedroom': 158,
 'min

In [26]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model=MultinomialNB()
spam_detect_model.fit(X_train,y_train)
y_pred=spam_detect_model.predict(X_test)
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_pred))
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

0.9829596412556054
              precision    recall  f1-score   support

           0       0.94      0.94      0.94       160
           1       0.99      0.99      0.99       955

    accuracy                           0.98      1115
   macro avg       0.97      0.96      0.97      1115
weighted avg       0.98      0.98      0.98      1115



TF-IDF

In [28]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.20)

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv=TfidfVectorizer(max_features=2500,ngram_range=(1,2))
X_train=tv.fit_transform(X_train).toarray()
X_test=tv.transform(X_test).toarray()

In [30]:
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [31]:
tv.vocabulary_

{'feel': 680,
 'like': 1171,
 'keep': 1077,
 'sleep': 1911,
 'text': 2085,
 'facebook': 664,
 'messag': 1306,
 'town': 2180,
 'feel like': 682,
 'aiyo': 44,
 'lesson': 1159,
 'earli': 589,
 'still': 1991,
 'haha': 893,
 'oki': 1502,
 'go': 805,
 'home': 954,
 'liao': 1164,
 'den': 522,
 'confirm': 404,
 'lor': 1209,
 'go home': 812,
 'call': 243,
 'close': 357,
 'hi': 931,
 'babi': 133,
 'im': 1005,
 'sat': 1794,
 'bloodi': 186,
 'bu': 226,
 'mo': 1337,
 'wont': 2421,
 'wanna': 2330,
 'somethin': 1936,
 'later': 1124,
 'back': 134,
 'jess': 1058,
 'xx': 2462,
 'call later': 257,
 'hey': 927,
 'pple': 1635,
 'night': 1445,
 'excel': 647,
 'locat': 1191,
 'wif': 2394,
 'ya': 2467,
 'dinner': 539,
 'togeth': 2159,
 'go dinner': 810,
 'what': 2385,
 'come': 383,
 'hill': 936,
 'hope': 959,
 'great': 858,
 'day': 490,
 'thing': 2108,
 'fine': 700,
 'busi': 231,
 'though': 2117,
 'hope great': 964,
 'great day': 859,
 'wait': 2318,
 'msg': 1385,
 'lt': 1236,
 'gt': 865,
 'min': 1312,
 'lt gt

In [32]:
from sklearn.naive_bayes import MultinomialNB
spam_tfidf_model = MultinomialNB().fit(X_train, y_train)
#prediction
y_pred=spam_tfidf_model.predict(X_test)
score=accuracy_score(y_test,y_pred)
print(score)
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))

0.979372197309417
              precision    recall  f1-score   support

           0       0.87      0.99      0.92       141
           1       1.00      0.98      0.99       974

    accuracy                           0.98      1115
   macro avg       0.93      0.98      0.96      1115
weighted avg       0.98      0.98      0.98      1115

